### ISSUE TITLE
er_main.py line118

### ISSUE THREAD

**Issue by yudahit** [optimass/Maximally_Interfered_Retrieval#1]
args.mem_size = args.mem_size*args.n_classes #convert from per class to total memory
or
args.buffer_size = args.mem_size*args.n_classes #convert from per class to total memory

**Comment by pclucas14** [comment]
Hi, 

could you explain a little more what the error is please ? 

Thanks,
Lucas

**Comment by eugenium** [comment]
This was resolved in offline emails
