### ISSUE TITLE
Mini-ImageNet data

### ISSUE THREAD

**Issue by JosephKJ** [optimass/Maximally_Interfered_Retrieval#4]
Hi, 

Thanks for the nice work! Can you please upload the Mini-ImageNet data that were used with this repo. 

It expects to be present at @eugenium 's /home. [Link](https://github.com/optimass/Maximally_Interfered_Retrieval/blob/master/data.py#L264)

Or, can you please share where I could download it from. This would help me maintain consistency with the reported results. 

Thanks!
Joseph

**Comment by eugenium** [comment]
You can download it using the instructions here https://github.com/cyvius96/prototypical-network-pytorch

**Comment by JosephKJ** [comment]
Thank you @eugenium !
