### ISSUE TITLE
Possible bug in the test accuracy calculation

### ISSUE THREAD

**Issue by phquang** [optimass/Maximally_Interfered_Retrieval#9]
Hi, I found a possible bug in the test accuracy calculation. For each task, you are averaging the accuracy across mini batches as the task accuracy. 

https://github.com/optimass/Maximally_Interfered_Retrieval/blob/c4522972a515b639a3687e6ecb01922c74216ca9/er_main.py#L204-L208

This calculation is wrong when the total number of data is not divisible by the mini batch size. Please consider changing to counting the total correctly predicted samples per task and then divide it by the total number of test data in that task.

**Comment by eugenium** [comment]
Thanks for pointing this out. If I undertood correctly this does not really affect our results or modifications that use the given dataloaders. We currently are not doing maintenance of this repo for minor issues (as we would need to backtest many things), but may take it up at another point in time, feel free also to submit a pull request.
